# Generated by Django 5.0.13 on 2025-11-30 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoNinos',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=50, unique=True)),
                ('edad_minima', models.IntegerField()),
                ('edad_maxima', models.IntegerField()),
                ('num_ninos_actual', models.IntegerField(default=0)),
                ('capacidad_maxima', models.IntegerField()),
                ('descripcion_actividades', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Grupos de Niños',
                'db_table': 'grupo_ninos',
            },
        ),
        migrations.CreateModel(
            name='PadreMadre',
            fields=[
                ('id_padre_madre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20)),
                ('relacion_con_nino', models.CharField(max_length=50)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Padres/Madres',
                'db_table': 'padre_madre',
            },
        ),
        migrations.CreateModel(
            name='PersonalGuarderia',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dni', models.CharField(max_length=20)),
                ('certificaciones', models.TextField(blank=True, null=True)),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('COMPLETO', 'Completo')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Personal de Guardería',
                'db_table': 'personal_guarderia',
            },
        ),
        migrations.CreateModel(
            name='ActividadGuarderia',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(max_length=100)),
                ('duracion_minutos', models.IntegerField()),
                ('material_requerido', models.TextField(blank=True, null=True)),
                ('es_obligatoria', models.BooleanField(default=True)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_guarderia.gruponinos')),
            ],
            options={
                'verbose_name_plural': 'Actividades de Guardería',
                'db_table': 'actividad_guarderia',
            },
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id_nino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('necesidades_especiales', models.TextField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('grupo_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_guarderia.gruponinos', to_field='nombre_grupo')),
                ('id_padre_madre_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_guarderia.padremadre')),
            ],
            options={
                'verbose_name_plural': 'Niños',
                'db_table': 'nino',
            },
        ),
        migrations.CreateModel(
            name='PagoMensualidad',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=50)),
                ('mes_correspondiente', models.DateField()),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('id_nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_guarderia.nino')),
            ],
            options={
                'verbose_name_plural': 'Pagos de Mensualidad',
                'db_table': 'pago_mensualidad',
            },
        ),
        migrations.AddField(
            model_name='gruponinos',
            name='id_personal_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_guarderia.personalguarderia'),
        ),
        migrations.CreateModel(
            name='AsistenciaNino',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estuvo_enfermo', models.BooleanField(default=False)),
                ('notas_dia', models.TextField(blank=True, null=True)),
                ('id_nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_guarderia.nino')),
                ('id_personal_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_guarderia.personalguarderia')),
            ],
            options={
                'verbose_name_plural': 'Asistencias de Niños',
                'db_table': 'asistencia_nino',
            },
        ),
    ]
